### PR TITLE
Allow skipping mvn or npm package manager updates

### PR DESCRIPTION
**Pull request by francoislg**
We wanted to use this tool, but we don't tave any Maven file in our repository. Update dependencies would fail when trying to execute any `mvn` command.

I added a simple property in the configuration file that allows disabling one of the two package managers. It should be backward compatible :)

Let me know if anything can be improved :)

I'll update the doc if this gets approved

### CODE REVIEW

**Comment by fredboutin** [comment]
In https://github.com/coveo/hg-auto-semver we decided to detect the package manager according to files in the repo. I think I'd rather do that. i.e.: if there is a pom.xml run maven, if not, skip. Thoughts?
TBH I thought it was this way already, but with a quick scan I didn't see any code checking this.

**Comment by francoislg** [comment]
🤔 Sure. I don't know Maven though, can you assume that if there is no "pom.xml" located in the project root, we can skip it? I see `mvn` commands, and checks for "Rules.xml" in the function, so I'm not quite sure if the pom file can be renamed.

Say in mvnOutdated:

```
if !fileExists(path + "/pom.xml") {
	log.Println("No pom.xml file was found. Skipping Maven.")
	return nil, make([]moduleVersion, 0, 0)
}
```

Note that this would be a functional change: Anyone that assumed the script would fail if the pom file is missing would now get an "ignoring Maven" message instead.

----

I also just noticed that npm is already skipped if there is no package.json, so it makes sense to skip mvn too, I just don't exactly know how to proceed without breaking stuff :)

**Comment by dreisch-coveo** [comment]
Personnally when things get too automatic I always get frustrated. But I like the convenience aspect too. I think its important that there at least be a a way to configure the behaviour if for some reason I don't want the default behaviour of running it on all the package managers in my project.

**Comment by fredboutin** [comment]
pom.xml will always be there or it will fail. As for the breaking change, I think it's not that breaking since it wasn't working anyway if you didn't have a pom.xml. Just add a log saying skipping to make sure someone debugging understand whats going on.

@dreisch-coveo I think we can keep this configuration then and if it's not present use the detection of files and if it's present use it?

**Comment by dreisch-coveo** [comment]
Sounds good to me

**Comment by francoislg** [comment]
☝️ mvn is now skipped if "pom.xml" does not exist for the given path. I have followed the format of the check in "npmOutdated". Let me know if you see something wrong 😸

**Review by fredboutin — APPROVED** [review]

**Comment by francoislg** [comment]
Are you people OK if I merge this? :)

**Comment by AndyCoveo** [comment]
Can you add an exemple of skipPackageManager in the README please :). Otherwise it looks good to me!

**Review by AndyCoveo — APPROVED** [review]

**Pull request merged**
